-- varrays PAGINA 179- 27/1/2015 -- 22/1/2016
CREATE TYPE TELEFONO AS VARRAY(3) OF VARCHAR2(9); 
/
DESC TELEFONO;

CREATE TABLE AGENDA 
(
  NOMBRE VARCHAR2(15),
  TELEF TELEFONO
);

DESC AGENDA;

--Insertamos varias filas:
SELECT * FROM AGENDA;

INSERT INTO AGENDA VALUES 
('MANUEL', 
   TELEFONO ('656008876', '927986655', '639883300')); 

INSERT INTO AGENDA (NOMBRE, TELEF) VALUES 
       ('MARTA', TELEFONO ('649500800'));
COMMIT;

SELECT * FROM AGENDA ;

--MODIFICION
UPDATE AGENDA 
  SET TELEF =  TELEFONO ('656008876', 
                         '927986655')
WHERE NOMBRE = 'MANUEL';

----------------------------------------------------
--RECORRER ELEMENTOS DEL ARRAY--
DECLARE
  CURSOR C1 IS SELECT * FROM AGENDA;
  CAD VARCHAR2(50);
BEGIN
  FOR I IN C1 LOOP
    DBMS_OUTPUT.PUT_LINE(I.NOMBRE ||
        ', Número de Telefonos: '||I.TELEF.COUNT);
    CAD:='*';
    FOR J IN 1 .. I.TELEF.COUNT LOOP   
      CAD:=CAD ||I.TELEF(J)||'*';
    END LOOP;
    DBMS_OUTPUT.PUT_LINE(CAD);
  END LOOP;
END;
/


------------------------------
--CREAR PROCEDIMIENTO PARA INSERTAR DATOS EN LA AGENDA
-- EL PROCEDIMIENTO RECIBE EL NOMBRE Y EL ARRAY DE TELEFONOS.
CREATE OR REPLACE PROCEDURE INSERTAR_AGENDA 
  ( N VARCHAR2, T TELEFONO) AS
BEGIN
  INSERT INTO AGENDA VALUES (N, T);
END INSERTAR_AGENDA;
/
--USO DEL PROCEDIMIENTO
BEGIN
  INSERTAR_AGENDA('LUIS', TELEFONO('949009977'));
  INSERTAR_AGENDA('MIGUEL', TELEFONO('949004020',
    '678905400'));
  COMMIT;
END;
/
SELECT * FROM AGENDA;
----------------------------------------------
--EJEMPLO QUE VISUALIZA TELEFONOS DE UN NOMBRE

DECLARE 
  TEL TELEFONO := TELEFONO(NULL, NULL, NULL); 
BEGIN
  SELECT TELEF INTO  TEL FROM AGENDA WHERE NOMBRE = 'MARTA';

  --Visualizar Datos
  DBMS_OUTPUT.PUT_LINE('Nº DE TELÉFONOS ACTUALES:   ' || TEL.COUNT);
  DBMS_OUTPUT.PUT_LINE('ÍNDICE DEL PRIMER ELEMENTO: ' || TEL.FIRST);
  DBMS_OUTPUT.PUT_LINE('ÍNDICE DEL ÚLTIMO ELEMENTO: ' || TEL.LAST);
  DBMS_OUTPUT.PUT_LINE('MÁXIMO Nº DE TLFS PERMITIDO:' || TEL.LIMIT);

  --Añade un número de teléfono a MARTA   
  TEL.EXTEND; 
  TEL(TEL.COUNT):= '123000000';     
  UPDATE AGENDA A SET A.TELEF = TEL WHERE NOMBRE = 'MARTA';   
    
  --Elimina un teléfono   
  SELECT TELEF INTO TEL FROM AGENDA WHERE NOMBRE = 'MANUEL';     
  TEL.TRIM;   --Elimina el último elemento del array    
  TEL.DELETE; --Elimina todos los elementos
  UPDATE AGENDA A SET A.TELEF = TEL WHERE NOMBRE = 'MANUEL';    
END;
/

--ACTIVIDAD 5

-------FIN EJJEMPLOS


