--------------------------------------------------------
-- Archivo creado  - lunes-junio-13-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TALUMNOS
--------------------------------------------------------

  CREATE TABLE "TALUMNOS" 
   (	"DNI" VARCHAR2(10 BYTE), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"DIRECCION" VARCHAR2(50 BYTE), 
	"POBLACION" VARCHAR2(50 BYTE), 
	"CODPOSTAL" NUMBER(5,0), 
	"PROVINCIA" VARCHAR2(40 BYTE), 
	"TELEFONO1" VARCHAR2(15 BYTE), 
	"TELEFONO2" VARCHAR2(15 BYTE), 
	"FECHA_NAC" DATE, 
	"ID_CURSO" NUMBER(4,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
/
--------------------------------------------------------
--  DDL for Table TASIGNATURAS
--------------------------------------------------------

  CREATE TABLE "TASIGNATURAS" 
   (	"COD_ASIG" NUMBER(4,0), 
	"NOMBRE" VARCHAR2(80 BYTE), 
	"TIPO" CHAR(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
/
--------------------------------------------------------
--  DDL for Table TCURSOS
--------------------------------------------------------

  CREATE TABLE "TCURSOS" 
   (	"ID_CURSO" NUMBER(4,0), 
	"DESCRIPCION" VARCHAR2(60 BYTE), 
	"NIVEL" VARCHAR2(30 BYTE), 
	"TURNO" CHAR(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
/
--------------------------------------------------------
--  DDL for Table TNOTAS
--------------------------------------------------------

  CREATE TABLE "TNOTAS" 
   (	"DNI" VARCHAR2(10 BYTE), 
	"COD_ASIG" NUMBER(4,0), 
	"NOTA1EV" NUMBER(4,2), 
	"NOTA2EV" NUMBER(4,2), 
	"NOTA3EV" NUMBER(4,2), 
	"NOTAFJUN" NUMBER(4,2), 
	"NOTASEPT" NUMBER(4,2)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
/
REM INSERTING into TALUMNOS
SET DEFINE OFF;
REM INSERTING into TASIGNATURAS
SET DEFINE OFF;
REM INSERTING into TCURSOS
SET DEFINE OFF;
REM INSERTING into TNOTAS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PKALUM
--------------------------------------------------------

  CREATE UNIQUE INDEX "PKALUM" ON "TALUMNOS" ("DNI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
/
--------------------------------------------------------
--  DDL for Index PKASIG
--------------------------------------------------------

  CREATE UNIQUE INDEX "PKASIG" ON "TASIGNATURAS" ("COD_ASIG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
/
--------------------------------------------------------
--  DDL for Index PKCURSOS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PKCURSOS" ON "TCURSOS" ("ID_CURSO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
/
--------------------------------------------------------
--  DDL for Index PKNOT
--------------------------------------------------------

  CREATE UNIQUE INDEX "PKNOT" ON "TNOTAS" ("DNI", "COD_ASIG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
/
--------------------------------------------------------
--  Constraints for Table TALUMNOS
--------------------------------------------------------

  ALTER TABLE "TALUMNOS" ADD CONSTRAINT "PKALUM" PRIMARY KEY ("DNI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
/
--------------------------------------------------------
--  Constraints for Table TASIGNATURAS
--------------------------------------------------------

  ALTER TABLE "TASIGNATURAS" ADD CONSTRAINT "PKASIG" PRIMARY KEY ("COD_ASIG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
/
--------------------------------------------------------
--  Constraints for Table TCURSOS
--------------------------------------------------------

  ALTER TABLE "TCURSOS" ADD CONSTRAINT "PKCURSOS" PRIMARY KEY ("ID_CURSO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
/
--------------------------------------------------------
--  Constraints for Table TNOTAS
--------------------------------------------------------

  ALTER TABLE "TNOTAS" ADD CONSTRAINT "PKNOT" PRIMARY KEY ("DNI", "COD_ASIG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
/
--------------------------------------------------------
--  Ref Constraints for Table TALUMNOS
--------------------------------------------------------

  ALTER TABLE "TALUMNOS" ADD CONSTRAINT "FKALUM" FOREIGN KEY ("ID_CURSO")
	  REFERENCES "TCURSOS" ("ID_CURSO") ENABLE;
/
--------------------------------------------------------
--  Ref Constraints for Table TNOTAS
--------------------------------------------------------

  ALTER TABLE "TNOTAS" ADD CONSTRAINT "FKNOT1" FOREIGN KEY ("COD_ASIG")
	  REFERENCES "TASIGNATURAS" ("COD_ASIG") ENABLE;
 
  ALTER TABLE "TNOTAS" ADD CONSTRAINT "FKNOT2" FOREIGN KEY ("DNI")
	  REFERENCES "TALUMNOS" ("DNI") ENABLE;
/
